"""
deepseek_supervisor.py
======================
DeepSeek-supervised correction loop for H2Q-Single FineWeb training.

Design:
  - Every N training chunks, sample a model generation and send to DeepSeek.
  - DeepSeek returns a quality-corrected / coherent continuation.
  - Save the response as a parquet file into the injection directory.
  - The AsyncBufferedLoader's _ingest_injection_files() picks it up automatically.

Security:
  - API key is NEVER hardcoded. Loaded from secrets_config.py → file or env var.
  - Key is never logged or printed.
  - Gracefully degrades to no-op if key is missing or API call fails.
"""

from __future__ import annotations

import os
import io
import sys
import time
import traceback
import random
from pathlib import Path
from typing import Optional

import pandas as pd
import requests

# ---------------------------------------------------------------------------
# Key loading (safe, never hardcoded)
# ---------------------------------------------------------------------------

def _load_api_key() -> Optional[str]:
    """Load DeepSeek API key from secret_config.py or environment variable.
    Returns None if not available (supervisor silently disabled).
    """
    try:
        from secret_config import get_deepseek_api_key
        return get_deepseek_api_key()
    except RuntimeError:
        return None
    except ImportError:
        # Fallback: try env var directly
        return os.getenv("H2Q_DEEPSEEK_API_KEY") or os.getenv("DEEPSEEK_API_KEY") or None


# ---------------------------------------------------------------------------
# DeepSeek API client
# ---------------------------------------------------------------------------

_DEEPSEEK_ENDPOINT = "https://api.deepseek.com/v1/chat/completions"
_DEEPSEEK_MODEL = "deepseek-chat"
_REQUEST_TIMEOUT = 60  # seconds


def _call_deepseek(
    api_key: str,
    user_text: str,
    system_prompt: str,
    max_tokens: int = 512,
) -> Optional[str]:
    """Send a single chat completion request to DeepSeek.
    Returns the assistant response text, or None on failure.
    """
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": _DEEPSEEK_MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_text},
        ],
        "max_tokens": max_tokens,
        "temperature": 0.7,
    }
    try:
        resp = requests.post(
            _DEEPSEEK_ENDPOINT,
            json=payload,
            headers=headers,
            timeout=_REQUEST_TIMEOUT,
        )
        resp.raise_for_status()
        data = resp.json()
        return data["choices"][0]["message"]["content"]
    except requests.exceptions.Timeout:
        print("[DeepSeek] ⚠️  API 请求超时，跳过本次监督。")
    except requests.exceptions.HTTPError as e:
        print(f"[DeepSeek] ⚠️  HTTP 错误: {e.response.status_code} - 跳过本次监督。")
    except Exception:
        print("[DeepSeek] ⚠️  未知错误，跳过本次监督：")
        traceback.print_exc()
    return None


# ---------------------------------------------------------------------------
# Main supervisor class
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = (
    "You are a high-quality text assistant. "
    "The user will give you a raw text fragment generated by a small language model. "
    "Your task: rewrite it into a coherent, fluent, factually plausible paragraph "
    "of similar length (150-300 words). "
    "Output only the rewritten text, no explanations."
)


class DeepSeekSupervisor:
    """
    Plugs into the qrlm_m4_evo training loop.

    Usage:
        supervisor = DeepSeekSupervisor(injection_dir, every_n_chunks=10)
        # Inside training loop, after each chunk:
        supervisor.maybe_supervise(chunk_counter, model, loader, device)
    """

    def __init__(
        self,
        injection_dir: str,
        every_n_chunks: int = 10,
        gen_tokens: int = 256,
        max_response_tokens: int = 512,
    ):
        self.injection_dir = Path(injection_dir)
        self.injection_dir.mkdir(parents=True, exist_ok=True)
        self.every_n_chunks = every_n_chunks
        self.gen_tokens = gen_tokens
        self.max_response_tokens = max_response_tokens

        self._api_key: Optional[str] = _load_api_key()
        if self._api_key:
            print(
                f"[DeepSeek] ✅ API 密钥已加载 (末4位: ...{self._api_key[-4:]})"
            )
            print(
                f"[DeepSeek] 监督周期: 每 {every_n_chunks} 个 chunk 触发一次注入。"
            )
        else:
            print(
                "[DeepSeek] ℹ️  未发现 API 密钥，监督功能已禁用（纯 FineWeb 自监督模式）。"
            )

    @property
    def enabled(self) -> bool:
        return self._api_key is not None

    def maybe_supervise(
        self,
        chunk_counter: int,
        model,
        loader,
        device,
    ) -> bool:
        """
        Call this after each chunk completes.
        Returns True if a supervision injection was written this call.
        """
        if not self.enabled:
            return False
        if chunk_counter == 0 or chunk_counter % self.every_n_chunks != 0:
            return False

        print(f"\n[DeepSeek] 🔬 Chunk {chunk_counter}: 触发监督注入...")
        try:
            raw_text = self._generate_sample(model, loader, device)
        except Exception:
            print("[DeepSeek] ⚠️  模型采样失败，跳过。")
            traceback.print_exc()
            return False

        if not raw_text.strip():
            print("[DeepSeek] ⚠️  模型生成为空，跳过。")
            return False

        print(f"[DeepSeek] 📤 发送 {len(raw_text)} 字节至 DeepSeek API...")
        corrected = _call_deepseek(
            api_key=self._api_key,
            user_text=raw_text[:2000],  # trim to avoid excessive token use
            system_prompt=_SYSTEM_PROMPT,
            max_tokens=self.max_response_tokens,
        )

        if not corrected:
            return False

        print(f"[DeepSeek] 📥 获得 {len(corrected)} 字节修正文本，写入注入目录...")
        self._write_injection_parquet(corrected, chunk_counter)
        print("[DeepSeek] ✅ 监督注入完成。")
        return True

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _generate_sample(self, model, loader, device) -> str:
        """Generate a short text sample from the current model state."""
        import torch
        import torch.nn.functional as F

        seed_options = [b"The", b"In", b"It", b"A", b"When", b"There"]
        seed_bytes = random.choice(seed_options)
        ctx = torch.tensor(
            [list(seed_bytes)],
            dtype=torch.long,
            device=device,
        )

        model.eval()
        with torch.no_grad():
            out = model.generate(ctx, self.gen_tokens)
        model.train()

        # Decode bytes; loader.decode strips null bytes
        raw_bytes = bytes([b for b in out[0].cpu().tolist() if 0 < b < 256])
        return raw_bytes.decode("utf-8", errors="ignore")

    def _write_injection_parquet(self, text: str, chunk_counter: int) -> None:
        """Save corrected text as a parquet file in the injection directory."""
        timestamp = int(time.time())
        filename = f"ds_supervision_{chunk_counter}_{timestamp}.parquet"
        filepath = self.injection_dir / filename

        df = pd.DataFrame({"text": [text]})
        df.to_parquet(filepath, index=False)
        print(f"[DeepSeek] 💾 注入文件: {filepath.name}")
